import { motion } from 'framer-motion';
import { Globe2, Layers, MapPin, MessageSquare, Search, ShieldCheck } from 'lucide-react';
import { Reveal, SectionHeading } from './primitives';
const items = [
  [Search, 'AI Search Visibility', 'Understand how your business appears across modern discovery experiences and where there is room to improve.', '01'],
  [Globe2, 'Website Optimization', 'Strengthen the technical foundation, structure, and content of your website so customers can find and choose you.', '02'],
  [MapPin, 'Local SEO', 'Strengthen the location-focused signals that help customers discover your business in the places they search.', '03'],
  [MessageSquare, 'Customer Conversations', 'Make it easier for customers to ask questions and for your team to respond consistently and professionally.', '04'],
  [Layers, 'One Connected Platform', 'Bring website, local search, business profile, reviews, content, and leads together in one workspace.', '05'],
  [ShieldCheck, 'Trust and Reputation', 'Build trust before customers call with consistent feedback monitoring and professional response workflows.', '06'],
];
export function WhyChooseUs() { return <section className="relative z-10 py-28 sm:py-36"><div className="mx-auto max-w-7xl px-6"><SectionHeading eyebrow="Why AIO Matrix" title={<>One platform for the work behind <span className="gradient-text">being found.</span></>} subtitle="The systems that shape your digital presence, connected so you can identify opportunities, take action, and keep improving." /><div className="relative mt-16"><div className="absolute left-[27px] top-2 bottom-2 w-px bg-gradient-to-b from-electric via-purple to-cyan sm:left-1/2" /><div className="space-y-8">{items.map(([Icon, title, description, tag], index) => { const ItemIcon = Icon as typeof Search; const left = index % 2 === 0; return <Reveal key={title as string} delay={index * .06}><div className={`relative flex items-start gap-6 sm:gap-0 ${left ? 'sm:flex-row' : 'sm:flex-row-reverse'}`}><div className="relative z-10 grid h-14 w-14 shrink-0 place-items-center rounded-2xl glass-strong text-white sm:absolute sm:left-1/2 sm:-translate-x-1/2"><ItemIcon size={22} strokeWidth={1.8} className="text-cyan" /></div><div className={`flex-1 sm:w-1/2 ${left ? 'sm:pr-16 sm:text-right' : 'sm:pl-16'}`}><motion.div whileHover={{ y: -4 }} className="rounded-2xl glass p-6"><div className={`mb-3 flex items-center gap-3 ${left ? 'sm:justify-end' : ''}`}><span className="font-mono text-xs text-white/35">{tag as string}</span><h3 className="font-display text-xl font-semibold text-white">{title as string}</h3></div><p className="text-sm leading-relaxed text-white/50">{description as string}</p></motion.div></div><div className="hidden sm:block sm:w-1/2" /></div></Reveal>; })}</div></div></div></section>; }
